# Generated by Django 5.2.7 on 2025-10-18 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido(s)')),
                ('profile_photo', models.ImageField(blank=True, db_column='foto_perfil', null=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil')),
                ('address', models.CharField(blank=True, db_column='direccion', max_length=255, verbose_name='Dirección')),
                ('phone_number', models.CharField(blank=True, db_column='telefono', max_length=20, verbose_name='Número de teléfono')),
                ('national_id', models.CharField(blank=True, db_column='dni', max_length=20, verbose_name='DNI')),
                ('city', models.CharField(blank=True, db_column='ciudad', max_length=100, verbose_name='Ciudad')),
                ('gender', models.CharField(blank=True, db_column='sexo', max_length=10, verbose_name='Sexo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario. Un usuario obtendrá todos los permisos otorgados a cada uno de sus grupos.', related_name='custom_user_set', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='Permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
