# Generated by Django 5.2.7 on 2025-10-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID Paciente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='pacientes/', verbose_name='Foto de Perfil')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('doctor_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to=settings.AUTH_USER_MODEL, verbose_name='Doctor Responsable')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAnemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateField(verbose_name='Fecha de Análisis')),
                ('imagen_conjuntiva', models.ImageField(upload_to='analisis/', verbose_name='Imagen Conjuntiva')),
                ('observaciones_clinicas', models.TextField(verbose_name='Observaciones Clínicas')),
                ('interpretacion_preliminar', models.TextField(verbose_name='Interpretación Preliminar')),
                ('grado_palidez', models.CharField(choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Severa', 'Severa'), ('Ninguna', 'Ninguna')], max_length=20, verbose_name='Grado de Palidez')),
                ('sospecha_diagnostica', models.TextField(verbose_name='Sospecha Diagnóstica')),
                ('recomendaciones', models.TextField(verbose_name='Recomendaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Reporte de Anemia',
                'verbose_name_plural': 'Reportes de Anemia',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
