# Generated by Django 5.2.7 on 2025-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto_perfil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='reporteanemia',
            name='imagen_conjuntiva',
            field=models.CharField(max_length=255, verbose_name='Imagen Conjuntiva'),
        ),
    ]
