# Generated by Django 5.2.7 on 2025-10-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paciente_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteanemia',
            name='confianza',
            field=models.FloatField(default=0.0, verbose_name='Confianza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanemia',
            name='nivel_confianza',
            field=models.CharField(default='Moderada', max_length=50, verbose_name='Nivel de Confianza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanemia',
            name='probabilidad',
            field=models.FloatField(default=0.0, verbose_name='Probabilidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporteanemia',
            name='tiene_anemia',
            field=models.BooleanField(default=False, verbose_name='Tiene Anemia'),
        ),
    ]
